import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { merriweather } from "../assets/fonts";
import Posts from "../components/Posts";

export default function Home() {
  return (
    <>
      <Head>
        <title>overreacted</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${merriweather.className}`}>
        <Posts />
      </main>
    </>
  );
}
